version: '3.3'
services:
  database:
    container_name: influxdb
    image: influx_image
    restart: always
    ports:
      - "8086:8086"
    env_file:
      - Services/influx/.env
    build:
      context: .
      dockerfile: Services/influx/Dockerfile
    networks:
      default:
        aliases:
          - influxdb

  broker:
    container_name: rabbit
    image: rabbit_image
    restart: always
    build:
      context: .
      dockerfile: Services/rabbit/Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"
    networks:
      default:
        aliases:
          - rabbit

  visualizador:
    container_name: grafana
    image: grafana_image
    restart: always
    build:
      context: .
      dockerfile: Services/grafana/Dockerfile
    ports:
      - "3000:3000"
      
  telegraf:
    image: telegraf_image
    container_name: telegraf
    restart: always
    build:
      context: .
      dockerfile: Services/telegraf/Dockerfile
    depends_on:
      - database
      - broker
    links:
      - database

  analitica:
    image: analitica_image
    container_name: analitica
    restart: always
    build:
      context: .
      dockerfile: Services/analitica/Dockerfile
    depends_on:
      - database
      - broker
      - telegraf
    links:
      - database
      - broker
      - telegraf
